### ISSUE TITLE
"src compman" vs. "scr compmsn" - Typo?

### ISSUE THREAD

**Issue by DanD222** [kedder/openvario-compman#2]
I've attempted to install compman following the installation instructions by inserting 
`src compman http://openvario.lebedev.lt/opkg/armv7vet2hf-neon` into _customfeeds.conf_ as per the instructions and then running `$ opkg install openvario-compman`.

This failed with the error message `opkg_prepare_url_for_install: Couldn't find anything to satisfy 'openvario-compman'`

I then ran Update from openvario-shell and noticed that the source for **compmsn** was updated.

After that, I was able to successfully install compman by running `$ opkg install openvario-compman`

Looking into _customfeeds.conf_, I can see that **"src compman" was changed to "src compmsn"**

I suspect that there's a typo somewhere :)

**Comment by kedder** [comment]
Hm, I can't find that typo and I don't believe any software is changing `customfeeds.conf` under the covers. I can't think any way `compmsn` appearing in customfeeds.conf other than you typed that in originally. Also, that name doesn't really affect the ability to install packages, and can be anything, including `compmsn`. It just have to be unique among your other feeds.

I suspect the first attempt failed because you didn't do `opkg update` before `opkg install`. openvario-shell is running `opkg update` so you were able to install compman after that.

**Comment by DanD222** [comment]
OK, I can’t seem to be able to reproduce it now on a fresh image install.

My only guess is that I didn’t re-enable USB tethering on my mobile phone after OV restarts, so opkg update wasn’t able to do its thing.

Probably shouldn’t be doing late-night installs and issue reports - sorry, and thanks!
